name: parto-pretérmino
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas>=1.5
  - numpy>=1.24
  - matplotlib>=3.7
  - seaborn>=0.12
  - scikit-learn>=1.2
  - xgboost>=1.7
  - joblib>=1.3
  - pip
  - pip:
      - gradio>=3.50
